add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[❯](bold green)"

[directory]
truncation_length = 3
truncation_symbol = "…/"
# repo_root_style = "bold cyan"
style = "white"
repo_root_format = "[$repo_root]($repo_root_style)[$path][$read_only]($read_only_style)"

[git_branch]
format = "[$branch]($style) "
#style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "red"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""
