require("luniox.plugins-setup")
require("luniox.core.options")
require("luniox.core.keymaps")
require("luniox.core.colorscheme")
require("luniox.plugins.comment")
require("luniox.plugins.nvim-tree")
require("luniox.plugins.lualine")
-- require("luniox.plugins.telescope")
require("luniox.plugins.nvim-cmp")
